CURRENCY_NAME = "Seeds"
CURRENCY_SYMBOL = "🍎"

MESSAGE_SEEDS = 1
MESSAGE_SEEDS_COOLDOWN = 180
MESSAGE_SEEDS_DAILY_LIMIT = 20

VOICE_SEEDS = 1
VOICE_SEEDS_INTERVAL_MINUTES = 10
VOICE_SEEDS_DAILY_LIMIT = 12

CASINO_MIN_BET = 10
CASINO_MAX_BET = 100

REASON_CASINO_BET = "casino_bet"
REASON_LEVEL = "level_reward"
REASON_EVENT = "event_reward"
REASON_SHOP = "shop_purchase"
REASON_ADMIN = "admin_adjustment"
REASON_CASINO_PAYOUT = "casino_payout"
REASON_CASINO_REFUND = "casino_refund"