CURRENCY_NAME = "Seeds"
CURRENCY_SYMBOL = "🌱"

MESSAGE_SEEDS = 1
MESSAGE_SEEDS_COOLDOWN = 180
MESSAGE_SEEDS_DAILY_LIMIT = 20

VOICE_SEEDS = 1
VOICE_SEEDS_INTERVAL_MINUTES = 10
VOICE_SEEDS_DAILY_LIMIT = 12

REASON_MESSAGE = "message_activity"
REASON_VOICE = "voice_activity"
REASON_LEVEL = "level_reward"
REASON_EVENT = "event_reward"
REASON_SHOP = "shop_purchase"
REASON_ADMIN = "admin_adjustment"